runtime: custom
env: flex

env_variables:
# the secret key used for the Django app (from PROJECT-DIRECTORY/settings.py)
  SECRET_KEY: '8(m)8e5a0*xt5q3(=63pgt2erwr!7r36!6dz=$f8o69$1qu9$8'
  DEBUG: 'False' # always False for deployment
  STATIC_URL: 'https://storage.googleapis.com/crawl-curation.appspot.com/static/'

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /.*
  script: crawl.wsgi.application
  secure: always

manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 20
